"""Shared constants for the Hermes Webhook Relay plugin."""

PLATFORM_NAME = "webhookrelay"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 3580
DEFAULT_PATH = "/webhookrelay"
DEFAULT_STATE_PATH = "~/.hermes/webhookrelay/state.db"
DEFAULT_MAX_BODY_BYTES = 1_048_576
DEFAULT_MAX_CONCURRENT = 4
DEFAULT_RUN_TIMEOUT_SECONDS = 300
DEFAULT_RETRY_AFTER_SECONDS = 15

KEY_ENV = "RELAY_KEY"
SECRET_ENV = "RELAY_SECRET"
PORT_ENV = "WEBHOOKRELAY_HERMES_PORT"
PATH_ENV = "WEBHOOKRELAY_HERMES_PATH"
